export const urlConstants = {
    login: '/login',
    logout: '/logout',
    attendencerecord: '/attendencerecord',
    location: '/location',
    user: '/user',
    leaves: '/user/leaves',
    applyLeave: '/user/apply/leaves',
    updateLeave: '/user/update/leaves',
    departments: '/departments',
    designations: '/designations',
    taxSaving: '/taxsaving',
    updateStatus :'/taxsaving/status',
    banks: '/user/banks',
    bank: '/user/bank',
    company: '/company/1',
    companyholiday: '/companyholiday',
    payrolls: '/payrolls',
    companypayroll: '/companypayroll',
    companyhours: '/companyhours',
    company1: '/company',
    companyleaves: '/companyleaves',
    timesheet: '/timesheet',
    regularization: '/user/regularization',
    applyRegularization: '/user/apply/regularization',
    updateRegularization: '/user/update/regularization',
    users: '/users',
    payroll:'/payroll',
    companygrade: '/companygrade',
    grades:'/user/grades',
    grade:'/user/grade',
    teams: '/user/teams',
    assets:'/assets',
    userAssets:'/user/assets',
    salary:'/user/salary/summary',
    salaryPayslip : '/user/salary/payslip',
    salaryBreakup :'/user/salary/breakup',
    payslipDownload: '/user/salary/payslip/download',
    tax: '/user/tax/declaration',
    taxDeclarationDocuments: '/user/tax/declaration/documents',
    myTax: '/user/tax',
    houseRent:'/user/house/rent',
    userProfile: '/user/profile',
    updateUserProfile: '/user/profile/details',
    updateUserAddress: '/user/profile/address',
    checkAttendance: '/user/check/attendance',
    companyTaxUpdate:'/companytax',
    payrollCalculateSalary:'/payroll/calc',
    resetPassword:'/user/change/password',
    form16PartA: '/tax/form16/part-a',
    form16PartB: '/tax/form16/part-b',
    advancedPayment: '/user/salary/advance',
    wfh:'/user/wfh/approval/records',
    HybrideWFH: '/user/wfh/advance/approval',
    officeWorkTime: '/company/emp/roster',
    compOff:'/user/comp-off',
    ApplyCompOff:'/user/apply/comp-off',
    updateCompOff:'/user/update/comp-off',
    updateProfilePic:'/user/profile/image',
    deleteProfilePic:'/user/profile/image/remove',
    companyLogo:'/company/logo',
    deleteCompanyLogo:'/company/logo',
    forceChangePassword:'/user/force/change/password',
    bulkEmployees:'/user/import',
    bulkDepartment: '/departments/import',
    bulkDesignation:'/designations/import',
    bulkSalaryBreakup:'/user/bulk/bank',
    userPayrollDownload: '/payrolls/download',
    userpayrollBanktransforDownload:'/payrolls/bank/transfer/download',
    updatePayroll:'/payroll/extra',
    attendanceAllowance:'/user/attendance/allowance',
    attendanceOt:'/user/ot',
    wfhApprovePrevRecords:'/user/wfh/approval/prev/records',
    updateWfh:'/user/wfh/approval/records',
    bulkTimesheet:'/timesheet/upload',
    wfhMyRecords:'/user/wfh/prev/logs',
    allLeaves:'/all/user/leaves',
    bulkLeaves:'/user/import/leaves',
    allTeamsPage:'/user/all/teams',
    allTeamsPageDownload:'/user/all/teams/excel',
    clearNotifications: '/notify/markall/read',
    startWork:'/worktime/start',
    stopWork:'/worktime/stop',
    inOutLogs:'/attendence/inout',
    allInOutLogs: '/attendence/all/inout',
    allTeamAttendancePage: '/user/all/teams/attendance',
    allTeamAttendanceDownload: '/user/all/teams/attendance/excel',
    attendanceNcns: '/user/attendance/ncns',
    companyShifts:'/company/all/shifts',
    companyShiftsUpdate:'/company/shift',
    userShift:'/user/all/shifts',
    userUpdateShift:'/user/shift',
    announcements:'/announcement',
    markAnnouncementRead:'/user/announcement/mark/read',
    pfEsicUpdate:'/user/pf_esic',
    viewCalculation:'/user/tax/view',
    calculationTax:'/user/tax/calc',
    userTaxCalculation:'/user/tax/calc/byuser',
    previousTax: '/user/previous/tax/deduction',
    previousIncentive: '/user/previous/incentive/given',
    savedIncentive:'/user/previous/tax/incentive',
    allTeamAttendance:'/user/all/teams/attendance',
    allAttendanceTeamDownload:'/user/all/teams/attendance/excel',
    bulkPreviousTax:'/user/previous/incentive/given/bulk',
    bulkPreviousIncentive:'user/previous/tax/deduction/bulk',
    updateAmount:'/taxsaving',
    allHouseRent:'/user/all/house/rent',
    updateAllHouseRent:'/user/all/house/rent',
    editAllHouseRent:'/user/all/house/rent',
    updateDocumentHouseRent:'/user/all/house/rent/document',
    allShiftPage:'/hr/all/shifts',
    allShiftListPage :'/company/hr/all/shifts',
    attendanceMetroCity:'/user/check/metrocity',
    otHours:'/user/all/teams/othours',
    editOtHours:'/user/all/teams/othours/edit'
};
